check

diff --git a/.github/workflows/reusable-workflow.yml b/.github/workflows/reusable-workflow.yml
--- a/.github/workflows/reusable-workflow.yml
+++ b/.github/workflows/reusable-workflow.yml
@@ -18,7 +18,14 @@ jobs:
       - env:
           URL: '${{ inputs.ingress-url }}'
         run: |
+              # curl https://$URL/live -s -k | jq -r .status | grep -i live
+              if [ -z "$URL" ]; then
+                echo "❌ ERROR: ingress-url input is empty!"
+                exit 1
+              fi
+              echo "✅ Checking endpoint: https://$URL/live"
               curl https://$URL/live -s -k | jq -r .status | grep -i live
+             
 
 
       
